// DELVE — the quarter library.
//
// Sixteen hand-drawn rooms turned eight ways is a hundred and twenty-eight
// boards, and a player recognises a repeat by the third sighting, so it plays
// like sixteen. This is the answer to that, and it needs no new art: the rooms
// are SLICED, and the slices recombine.
//
// THE GEOMETRY
//
//   # # # # # # # # # # #    An 11x11 floor is a border, a SPINE — the middle
//   # N N N N s N N N N #    row and middle column of the interior, twenty-one
//   # N N N N s N N N N #    tiles that are always open — and four 4x4 quarters.
//   # N N N N s N N N N #
//   # N N N N s N N N N #    Each quarter touches the spine along exactly two
//   # s s s s s s s s s #    of its edges.
//   # S S S S s S S S S #
//   # S S S S s S S S S #    The shape of this does not depend on the number:
//   # S S S S s S S S S #    the spine sits at (W-1)/2 and a quarter is (W-3)/2
//   # S S S S s S S S S #    across, so the same theorem held at 9x9 with 3x3
//   # # # # # # # # # # #    quarters and holds here with 4x4.
//
// THE THEOREM
//
// If every open cell in a quarter reaches one of those two edges FROM INSIDE
// THE QUARTER, it reaches the spine; and the spine reaches everything. So four
// separately-valid quarters compose into a connected floor. Always. No global
// check, no retry loop — the old generator rolled the dice up to forty times
// hoping for a floor that worked, and a generator that retries until it likes
// the answer quietly prefers the safest possible answer.
//
// (Two open groups inside one quarter that BOTH touch the spine are fine: they
// are joined to each other through the spine. The check allows that on purpose.)
//
// EIGHT PLACEMENTS, ALL FREE
//
// Quarters are authored in NW form — spine to the east and to the south. The
// other three corners are reflections, and a reflection maps those two edges
// onto whichever two edges touch the spine there. The transpose swaps east with
// south, so it is NW form too. One validation, eight placements, all provably
// connected.
//
// LEGEND — as rooms.js, plus the tags, which are hints and not commitments:
//   .  floor      #  pillar      :  rubble      _  gap      ?  maybe-rubble
//   *  a good place for loot     e  a good place for something to stand
//   >  a good place for a stair
// The assembler decides what actually goes where, because a floor needs exactly
// one spawn and exactly two stairs and no single quarter can promise that.
//
// HARVESTED, NOT AUTHORED. This file is generated by slicing rooms.js — every
// entry is named for the room and corner it came from. Redraw a room and this
// is regenerated; do not hand-edit it.

export const QUARTERS = [
  { id: 'larder-N', cells: [">.?#",".###",".*#?",".#.#"] },
  { id: 'larder-E', cells: ["e>?#",".###",".*##",".#.#"] },
  { id: 'larder-S', cells: ["...?",".#.#","e:#e",".###"] },
  { id: 'larder-W', cells: ["....",".#.#",".e##",".###"] },
  { id: 'vault-N', cells: ["....","####",".#**",">#*e"] },
  { id: 'vault-E', cells: ["e..>",".?#?","..#?",".?.."] },
  { id: 'vault-S', cells: ["...:",".#.#","e#..","####"] },
  { id: 'vault-W', cells: ["....","..##","e..:",".###"] },
  { id: 'split-N', cells: ["....",".###",">#e?",".#.#"] },
  { id: 'split-E', cells: ["e.>.",".###",".#e.",".#.#"] },
  { id: 'split-S', cells: ["..##",".###",".#*.",".#.#"] },
  { id: 'split-W', cells: ["....",".###",".#*:",".#.#"] },
  { id: 'crossing-N', cells: [".#..",">##?","..._","?.__"] },
  { id: 'crossing-E', cells: ["e>..",".##?","..#_",":.__"] },
  { id: 'crossing-S', cells: ["...:",".##e","..#_",":._*"] },
  { id: 'crossing-W', cells: ["....",".##.","..#_","?._e"] },
  { id: 'rubblefield-N', cells: [".#:.","..?#",":.#.","..:*"] },
  { id: 'rubblefield-E', cells: ["e#.:","...?",">#:#",".#.#"] },
  { id: 'rubblefield-S', cells: ["..?.","e.?#","?...","..?e"] },
  { id: 'rubblefield-W', cells: ["..:.",".##?","..?.","#.#."] },
  { id: 'gauntlet-N', cells: ["....","?#.#","#>..","?#:#"] },
  { id: 'gauntlet-E', cells: ["e>..","?#?#","....",":#.#"] },
  { id: 'gauntlet-S', cells: ["....","?#?#","...*",":#.#"] },
  { id: 'gauntlet-W', cells: ["....","?#.#","...*","?#:#"] },
  { id: 'twohalls-N', cells: ["....",">###","e...",".###"] },
  { id: 'twohalls-E', cells: ["e>..","####","??..",".###"] },
  { id: 'twohalls-S', cells: ["....",".###","??..","####"] },
  { id: 'twohalls-W', cells: ["....",".###","e...",".###"] },
  { id: 'comb-N', cells: [".#?.",">#?#",".#.?",".#.#"] },
  { id: 'comb-E', cells: ["e>.#",".###",".*##",".#.#"] },
  { id: 'comb-S', cells: [".e..",".#.#",".*#.",".###"] },
  { id: 'comb-W', cells: ["....",".#.#","..#?",".###"] },
  { id: 'antechamber-N', cells: ["..#?",".:?#","...#","##.#"] },
  { id: 'antechamber-E', cells: ["e...",".#.#",".?##",".###"] },
  { id: 'antechamber-S', cells: ["....",".###","e.#?",".###"] },
  { id: 'antechamber-W', cells: [".e..",".#.#","*.#:","####"] },
  { id: 'pincer-N', cells: ["..._",".?##",".#*>",".#?#"] },
  { id: 'pincer-E', cells: ["e___",">?##",".#*.",".#.#"] },
  { id: 'pincer-S', cells: ["....","..##",".#e.",".###"] },
  { id: 'pincer-W', cells: ["....","..##",".#e.",".#.#"] },
  { id: 'spiral-E', cells: ["..>.",".###",".#..",".#.#"] },
  { id: 'spiral-S', cells: ["....",".###",".#..",".#.#"] },
  { id: 'spiral-W', cells: ["....",".###","?#.e","##.#"] },
  { id: 'ledges-N', cells: [">.##",".?__",".?_?",".#.."] },
  { id: 'ledges-E', cells: ["e...",">?__",".._#",".#.#"] },
  { id: 'ledges-S', cells: ["....","..__",":._#",".#.."] },
  { id: 'ledges-W', cells: ["....","..__",".._#",".#.."] },
  { id: 'well-N', cells: [">###",".###",".#*?",".#._"] },
  { id: 'well-E', cells: ["e...",">###",".#*.",".#._"] },
  { id: 'well-S', cells: ["....",".###",".#e.",".#._"] },
  { id: 'shooting-N', cells: [".#..",".???",">.##",".#.#"] },
  { id: 'shooting-E', cells: ["e#>#","...?","..#.",".#.."] },
  { id: 'shooting-S', cells: ["....","e...","..#.","...."] },
  { id: 'shooting-W', cells: ["....","e...","..#.",".#.#"] },
  { id: 'cells-N', cells: ["..#e","..#.",".##.",".>.."] },
  { id: 'cells-E', cells: ["..#>","?.#.","..##",".?#."] },
  { id: 'cells-S', cells: ["#...","*.#e",".##.","#..."] },
  { id: 'cells-W', cells: ["....","*.#.","#.##","...#"] },
  { id: 'causeway-N', cells: ["...?",".?..","____","____"] },
  { id: 'causeway-E', cells: ["e.>.","..??","____","____"] },
  { id: 'causeway-S', cells: ["....","..*.","____","____"] },
  { id: 'causeway-W', cells: ["....","e.*.","____","____"] },
];
